"""
RailPway_Technical

Module : create_repository_structure.py

Purpose
-------
Create the complete directory structure for the
RailPway_Technical project and place a README.md
inside every folder so Git can track it.

Author : Sirshendu Karmakar
Version : 1.0.0
"""

from pathlib import Path


PROJECT_STRUCTURE = {
    "src": {
        "config": {},
        "models": {},
        "gui": {},
        "generators": {},
        "assemblers": {},
        "word": {},
        "images": {},
        "database": {},
        "utils": {},
    },
    "handbook": {
        "config": {},
        "text": {},
        "images": {},
        "diagrams": {},
        "references": {},
        "templates": {},
        "output": {},
    },
    "output": {
        "DOCX": {},
        "PDF": {},
        "HTML": {},
        "EPUB": {},
    },
    "templates": {},
    "image_library": {
        "Photos": {},
        "Diagrams": {},
        "Icons": {},
        "Logos": {},
        "Attribution": {},
    },
    "references": {
        "IRPWM": {},
        "USSOR": {},
        "RDSO": {},
        "IRS": {},
        "Tender": {},
    },
    "docs": {
        "UserGuide": {},
        "DeveloperGuide": {},
        "Architecture": {},
        "Screenshots": {},
        "API": {},
    },
    "tests": {},
    ".github": {
        "workflows": {},
        "ISSUE_TEMPLATE": {},
    },
}


README_TEXT = """# {folder}

This folder is part of the **RailPway_Technical** project.

Purpose
-------
{purpose}

> Auto-generated by create_repository_structure.py
"""


PURPOSE = {
    "src": "Application source code.",
    "config": "Application configuration modules.",
    "models": "Business data models.",
    "gui": "CustomTkinter graphical user interface.",
    "generators": "Word and handbook generators.",
    "assemblers": "Volume and handbook assemblers.",
    "word": "Microsoft Word document utilities.",
    "images": "Image processing modules.",
    "database": "SQLite database modules.",
    "utils": "Utility modules.",
    "handbook": "Handbook source content.",
    "text": "Chapter text files.",
    "diagrams": "Engineering diagrams.",
    "references": "Reference documents.",
    "templates": "Word templates.",
    "output": "Generated output.",
    "DOCX": "Generated Word documents.",
    "PDF": "Generated PDF documents.",
    "HTML": "Generated HTML files.",
    "EPUB": "Generated EPUB files.",
    "image_library": "Master image repository.",
    "Photos": "Photographs.",
    "Diagrams": "Engineering drawings.",
    "Icons": "Icons.",
    "Logos": "Company logos.",
    "Attribution": "Image attribution files.",
    "IRPWM": "IRPWM reference documents.",
    "USSOR": "USSOR reference documents.",
    "RDSO": "RDSO documents.",
    "IRS": "IRS specifications.",
    "Tender": "Tender reference documents.",
    "docs": "Project documentation.",
    "UserGuide": "User Guide.",
    "DeveloperGuide": "Developer Guide.",
    "Architecture": "Architecture documents.",
    "Screenshots": "Screenshots.",
    "API": "API documentation.",
    "tests": "Unit tests.",
    ".github": "GitHub configuration.",
    "workflows": "GitHub Actions workflows.",
    "ISSUE_TEMPLATE": "Issue templates.",
}


def create_structure(base_path: Path, tree: dict):
    """
    Recursively create folder structure.
    """

    for folder, children in tree.items():

        current = base_path / folder
        current.mkdir(parents=True, exist_ok=True)

        readme = current / "README.md"

        if not readme.exists():
            readme.write_text(
                README_TEXT.format(
                    folder=folder,
                    purpose=PURPOSE.get(folder, "Project folder."),
                ),
                encoding="utf-8",
            )

        create_structure(current, children)


def create_root_files(root: Path):
    """
    Create repository root files.
    """

    files = {
        "README.md": "# RailPway_Technical\n\n"
                     "Basic Technical Reference for Railway Permanent Way Maintenance\n",

        ".gitignore": """__pycache__/
*.pyc
*.pyo
*.pyd
*.log
.venv/
.vscode/
.idea/
*.db
""",

        "CHANGELOG.md": "# Changelog\n",

        "CONTRIBUTING.md": "# Contribution Guide\n",

        "LICENSE": "MIT License\n",

        "requirements.txt": "",

        "pyproject.toml": """[project]
name = "RailPway_Technical"
version = "0.1.0"
requires-python = ">=3.12"
""",
    }

    for filename, content in files.items():

        file_path = root / filename

        if not file_path.exists():
            file_path.write_text(content, encoding="utf-8")


def main():

    print("=" * 60)
    print("RailPway_Technical Repository Creator")
    print("=" * 60)

    repository = Path(
        input("\nEnter full path of local GitHub repository:\n> ").strip()
    )

    repository.mkdir(parents=True, exist_ok=True)

    create_structure(repository, PROJECT_STRUCTURE)

    create_root_files(repository)

    print("\nRepository structure created successfully.\n")
    print(repository)


if __name__ == "__main__":
    main()